apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qp5vsquut-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qp5vsquut-go 
  name: qp5vsquut-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qp5vsquut-go 
