apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: qp5vsquut-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtaptestqa/rhtap-qe:1b7ad35a4098958bf3129c4412a70fced0e85d7e@sha256:ec10be13cda29d1aabceb319b288e24b550ddb995aad6b0210557e796bee9564
          name: container-image
